apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.postgres.name }}
    deployment: {{ .Values.postgres.name }}
  name: {{ .Values.postgres.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
      deployment: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
        deployment: {{ .Values.postgres.name }}
    spec:
      containers:
      - env:
          - name: POSTGRESQL_DATABASE
            value: {{ .Values.postgres.schema }}
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.postgres.password }}
          - name: POSTGRESQL_USER
            value: {{ .Values.postgres.user }}
        image: {{ .Values.postgres.image }}
        name: {{ .Values.postgres.name }}
        ports:
          - containerPort: 5432
            protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: "{{ .Values.postgres.name }}-volume-1"
      volumes:
        - emptyDir: {}
          name: "{{ .Values.postgres.name }}-volume-1"
