apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: {{ .Values.postgres.name }}
  name: {{ .Values.postgres.name }}
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/imported-from: {{ .Values.postgres.image }}
      from:
        kind: DockerImage
        name: {{ .Values.postgres.image }}
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
