apiVersion: "v1"
kind: "Secret"
metadata:
  name: "my-database-secret"
  labels:
    app.kubernetes.io/part-of: crud-example
    app.kubernetes.io/name: crud-service
    app.kubernetes.io/component: frontend
    app.openshift.io/runtime: rh-spring-boot
    app.openshift.io/runtime-version: ${spring-boot.version}
  annotations:
    app.kubernetes.io/vcs-uri: git@github.com:snowdrop/crud-example.git
    app.kubernetes.io/connects-to: crud-db
stringData:
  user: "luke"
  password: "secret"
