apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    app.kubernetes.io/part-of: crud-example
    app.kubernetes.io/name: crud-service
    app.kubernetes.io/component: frontend
    app.kubernetes.io/runtime: snowdrop
    app.kubernetes.io/runtime-version: ${spring-boot.version}
  annotations:
    app.kubernetes.io/vcs-uri: git@github.com:snowdrop/crud-example.git
    app.kubernetes.io/connects-to: crud-db
spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: user
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: password
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"
