apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: my-database
      deployment: my-database
    name: my-database
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: my-database
        deployment: my-database
    template:
      metadata:
        labels:
          app: my-database
          deployment: my-database
      spec:
        containers:
        - env:
            - name: POSTGRESQL_DATABASE
              value: my_data
            - name: POSTGRESQL_PASSWORD
              value: secret
            - name: POSTGRESQL_USER
              value: luke
          image: quay.io/centos7/postgresql-13-centos7:1
          name: my-database
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: my-database-volume-1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
        volumes:
        - emptyDir: {}
          name: my-database-volume-1
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: my-database
    name: my-database
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: my-database
      deployment: my-database
  status:
    loadBalancer: {}
kind: List
metadata: {}
