app:
  name: crud
  version: 2.7-SNAPSHOT
  docker:
    image: quay.io/snowdrop/spring-boot-crud-example:2.7
  env:
    - name: spring.datasource.url
      value: jdbc:postgresql://my-database:5432/my_data
    - name: spring.datasource.username
      value: luke
    - name: spring.datasource.password
      value: secret
    - name: spring.datasource.driver-class-name
      value: org.postgresql.Driver
    - name: spring.jpa.hibernate.ddl-auto
      value: create
postgres:
  name: my-database
  schema: my_data
  image: quay.io/centos7/postgresql-13-centos7:1
  user: luke
  password: secret
